config/routes.rb
Rails.application.routes.draw do
  scope :module => :staypuft do
    resources :deployments do
      collection do
        get 'auto_complete_search'
      end
      member do
        post 'deploy'
        get 'populate'
        get 'summary'
        get 'edit'
        post 'associate_host'
        post 'unassign_host'
        get 'export_config'
        post 'import_config'
        get 'refresh_assigned_hosts'
      end

      resources :steps

      resources :interface_assignments, :only => [:index, :create, :destroy]

      resources :bonds, :only => [:create, :destroy] do
        member do
          put 'add_slave'
          put 'remove_slave'
          put 'change_mode'
        end
      end
    end

    resources :subnet_typings, :only => [:create, :destroy, :update]

    scope 'staypuft', as: 'staypuft' do
      resources :subnets
    end
  end
end

app/models/concerns/staypuft/puppetclass_extensions.rb
module Staypuft::PuppetclassExtensions
  extend ActiveSupport::Concern

  included do
    has_many :role_classes, :dependent => :destroy, :class_name => 'Staypuft::RoleClass'
    has_many :roles, :through => :role_classes, :class_name => 'Staypuft::Role'

    has_many :service_classes, :dependent => :destroy, :class_name => 'Staypuft::ServiceClass'
    has_many :services, :through => :service_classes, :class_name => 'Staypuft::Service'

  end
end

app/models/settings/staypuft.rb
class Setting::Staypuft < ::Setting
  BLANK_ATTRS << "base_hostgroup"

  def self.load_defaults
    # Check the table exists
    return unless super

    # fixme: not sure about the best way to store AR objects in settings.
    # for now, since we know type, store ID. It might be good to add custom
    # get/set code to decode the ID value into a hostgroup (which methods to call?)
    Setting.transaction do
      [
       self.set("base_hostgroup", _("The base hostgroup which contains the base provisioning config"), nil)
      ].compact.each { |s| self.create s.update(:category => "Setting::Staypuft")}
    end

    true

  end

end

app/models/staypuft/concerns/environment_extensions.rb
module Staypuft::Concerns::EnvironmentExtensions
  extend ActiveSupport::Concern

  module ClassMethods
    def get_discovery
      find_by_name('discovery') or
          raise ::Staypuft::Exception,
                'missing discovery environment, which ensures all its machines are booted ' +
                    'to discovery image.'
    end

    def get_or_create_provisioning
      where(name: 'provisioning').first_or_create
    end
  end
end

app/models/staypuft/concerns/host_details_helper.rb
module Staypuft
  module Concerns
    module HostDetailsHelper
      extend ActiveSupport::Concern

      # Returns memory in GB
      def mem
        mem_arr = self.facts_hash["memorytotal"]
        if mem_arr
          mem_str, mem_unit = mem_arr.split(" ")
          mem_number = mem_str.to_f
          case mem_unit
          when "MB"
            mem_number / 1024
          when "GB"
            mem_number
          when "TB"
            mem_number * 1024
          else
            nil
          end
        else
          nil
        end
      end

      # Returns total number of processes
      def cpus
        self.facts_hash["processorcount"]
      end

      # Returns model
      def model_type
        self.facts_hash["hardwaremodel"]
      end

      # Returns array of NIC names
      def network_interfaces
        if self.facts_hash["interfaces"]
          self.facts_hash["interfaces"].split(",")
        else
          nil
        end
      end

      # Returns architecture
      def architectures
        if self.facts_hash["architecture"]
          self.facts_hash["architecture"].name
        else
          nil
        end
      end

      # Returns array of block device names
      def blockdevices
        if self.facts_hash["blockdevices"]
          self.facts_hash["blockdevices"].split(",")
        else
          []
        end
      end
    end
  end
end

app/models/staypuft/concerns/host_fencing_extensions.rb
module Staypuft
  module Concerns
    module HostFencingExtensions
      extend ActiveSupport::Concern

      FENCING_TYPES = {
        'fence_ipmilan' => 'IPMI'
      }

      included do
        define_method :fencing do
          instance_variable_get(:@fencing_config) or
            instance_variable_set(:@fencing_config, ::Staypuft::Fencing.new(self))
        end

        define_method :fencing= do |value|
          fencing.update(value)
        end

        validates_associated :fencing
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :bmc_nic
end

app/models/staypuft/concerns/host_interface_management.rb
module Staypuft
  module Concerns
    module HostInterfaceManagement
      extend ActiveSupport::Concern

      included do

      end

      def clean_vlan_interfaces
        self.interfaces.virtual.map(&:destroy)
      end

      def interfaces_identifiers
        interfaces = [ self.primary_interface ]
        interfaces += self.respond_to?(:interfaces) ? self.interfaces.where("type <> 'Nic::BMC'").physical.map(&:identifier) : []
        interfaces
      end

      def interfaces_identifiers_with_subnets
        interfaces = [ [self.primary_interface, self.subnet.name] ]
        if self.respond_to?(:interfaces)
          interfaces += self.interfaces.where("type <> 'Nic::BMC'").physical.map do |interface|
            [interface.identifier, ((sub = interface.subnet) ? sub.name :  "")]
          end
        end
        interfaces
      end

      def make_all_interfaces_managed
        self.interfaces.each do |interface|
          interface.managed = true
          interface.save!
        end
      end

      def network_query
        @network_query || NetworkQuery.new(self.hostgroup.deployment, self)
      end

      def primary_interface_is_bonded?
        self.bond_interfaces.any? do |bond|
          bond.attached_devices_identifiers.any? do |interface_identifier|
            self.has_primary_interface? ? self.primary_interface == interface_identifier : false
          end
        end
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :network_query, :primary_interface_is_bonded?
end

app/models/staypuft/concerns/host_open_stack_affiliation.rb
module Staypuft
  module Concerns
    module HostOpenStackAffiliation
      extend ActiveSupport::Concern

      included do
        scope(:in_deployment, lambda do |deployment|
          joins(hostgroup: :deployment_role_hostgroup).
              where(DeploymentRoleHostgroup.table_name => { deployment_id: deployment })
        end)

        scope(:in_roles, lambda do |*roles|
          joins(hostgroup: :deployment_role_hostgroup).
              where(DeploymentRoleHostgroup.table_name => { role_id: roles })
        end)

        scope :in_role, lambda { |role| in_roles(role) }

        has_one :deployment, through: :hostgroup
      end


      def open_stack_deployed?
        !deployment.nil? && !deployment.in_progress? &&
        open_stack_environment_set? && open_stack_assigned?
      end

      def open_stack_environment_set?
        open_stack_assigned? &&
        respond_to?(:environment) &&
        environment != Environment.get_discovery
      end

      def open_stack_assigned?
        respond_to?(:hostgroup) &&
            hostgroup.try(:parent).try(:parent) == Hostgroup.get_base_hostgroup
      end

      def open_stack_unassign
        self.hostgroup = nil
        save!
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :deployment
end

app/models/staypuft/concerns/host_orchestration_build_hook.rb
module Staypuft
  module Concerns
    module HostOrchestrationBuildHook
      extend ActiveSupport::Concern

      included do
        before_provision :wake_up_orchestration
      end

      def wake_up_orchestration
        key = HostOrchestrationBuildHook.cache_id(id)
        ids = Rails.cache.read(key)
        Rails.cache.delete key
        ForemanTasks.dynflow.world.event *ids.values_at(:execution_plan_id, :step_id),
                                         installed_at: installed_at
      end

      def self.cache_id(host_id)
        "host.#{host_id}.wake_up_orchestration"
      end

    end
  end
end

app/models/staypuft/concerns/hostgroup_extensions.rb
module Staypuft::Concerns::HostgroupExtensions
  extend ActiveSupport::Concern

  included do
    has_one :deployment_role_hostgroup, :dependent => :destroy, :class_name => 'Staypuft::DeploymentRoleHostgroup'
    has_one :parent_deployment, :through => :deployment_role_hostgroup, :class_name => 'Staypuft::Deployment', :source => :deployment
    has_one :role, :through => :deployment_role_hostgroup, :class_name => 'Staypuft::Role'

    has_one :deployment, :class_name => 'Staypuft::Deployment', through: :deployment_role_hostgroup

    scope :deploy_order,
          lambda { reorder "#{::Staypuft::DeploymentRoleHostgroup.table_name}.deploy_order" }
  end

  def add_puppetclasses_from_resource(resource)
    if resource.respond_to?(:puppetclasses)
      resource.puppetclasses.each do |puppetclass|
        unless puppetclasses.include?(puppetclass)
          puppetclasses << puppetclass
        end
      end
    end
  end

  def current_param_value(key)
    lookup_value = LookupValue.where(:lookup_key_id => key.id, :id => lookup_values).first
    if lookup_value
      [lookup_value.value, to_label]
    else
      inherited_lookup_value(key)
    end
  end

  def current_param_value_str(key)
    lookup_value, _ = current_param_value(key)
    return key.value_before_type_cast(lookup_value)
  end

  def set_param_value_if_changed(puppetclass, key, value)
    lookup_key         = puppetclass.class_params.where(:key => key).first
    lookup_value_value = current_param_value(lookup_key)[0]
    current_value      = lookup_key.value_before_type_cast(lookup_value_value).to_s.chomp
    if current_value != value
      lookup       = LookupValue.where(:match         => hostgroup.send(:lookup_value_match),
                                       :lookup_key_id => lookup_key.id).first_or_initialize
      lookup.value = value
      lookup.save!
    end
  end

  def free_hosts
    Host::Base.where('hostgroup_id IS NULL')
  end

  # Returns all hosts associated with this hostgroup with the openstack
  # deployment environment set.  These can be filtered based by setting
  # errors=true or errors=false to return only the hosts  with no errors or
  # with errors respectively.
  def openstack_hosts(errors=nil)
    oshosts = hosts.select { |h| h.open_stack_environment_set? }

    unless errors.nil?
      oshosts.select! { |h| (!errors ^ h.error?) }
    end
    oshosts
  end

  module ClassMethods
    def get_base_hostgroup
      Hostgroup.where(:name => Setting[:base_hostgroup]).first or raise 'missing base_hostgroup'
    end
  end

  Gem::Version.new(SETTINGS[:version].notag) < Gem::Version.new('1.5') and
      Rails.logger.warn 'Foreman 1.5 is required for nesting of Hostgroups to work properly,' +
                            "please upgrade or expect failures.\n#{__FILE__}:#{__LINE__}"
end

app/models/staypuft/concerns/lookup_key_extensions.rb
module Staypuft::Concerns::LookupKeyExtensions
  extend ActiveSupport::Concern

  included do
    alias_method_chain :cast_validate_value, :erb
    alias_method_chain :value_before_type_cast, :limpet

    # apply only when this extension is included
    ::Staypuft::Concerns::LookupKeyExtensions.monkey_path_safe_render
  end

  LIMPET_FORMAT        = '<%%={key_id:%s};'
  LIMPET_FORMAT_REGEXP = /#{LIMPET_FORMAT % '(\d+)'}/

  def cast_validate_value_with_erb(value)
    if has_erb? value
      if value =~ LIMPET_FORMAT_REGEXP
        value.gsub(/#{LIMPET_FORMAT_REGEXP}/, LIMPET_FORMAT % id)
      else
        value.gsub(/<%=/, LIMPET_FORMAT % id)
      end
    else
      cast_validate_value_without_erb value
    end
  end

  def cast_validate_value_after_erb(value, type)
    method = "cast_value_#{type}".to_sym
    return value unless self.respond_to? method, true
    self.send(method, value) rescue raise TypeError
  end

  def self.has_erb?(value)
    value =~ /<%.*%>/
  end

  def has_erb?(value)
    Staypuft::Concerns::LookupKeyExtensions.has_erb? value
  end

  def self.evaluate_value(hostgroup, value)
    host = Host::Managed.new(hostgroup: hostgroup, name: 'renderer')
    SafeRender.new(:variables => { :host => host }).parse(value)
  rescue => e
    "ERROR: #{e.message} (#{e.class})"
  end

  def value_before_type_cast_with_limpet(value)
    if has_erb? value
      value.gsub(LIMPET_FORMAT_REGEXP, '<%=')
    else
      value_before_type_cast_without_limpet(value)
    end
  end

  def self.monkey_path_safe_render
    ::SafeRender.class_eval do
      def parse_string(string)
        raise ::ForemanException.new(N_('SafeRender#parse_string was passed a %s instead of a string') % string.class) unless string.is_a? String

        lookup_key_id = string[Staypuft::Concerns::LookupKeyExtensions::LIMPET_FORMAT_REGEXP, 1]
        if lookup_key_id
          lookup_key = LookupKey.find(lookup_key_id)
          type       = lookup_key.key_type
        end

        value = if Setting[:safemode_render]
                  box = Safemode::Box.new self, @allowed_methods
                  box.eval(ERB.new(string, nil, '-').src, @allowed_vars)
                else
                  @allowed_vars.each { |k, v| instance_variable_set "@#{k}", v }
                  ERB.new(string, nil, '-').result(binding)
                end

        if type
          lookup_key.cast_validate_value_after_erb value, type
        else
          value
        end
      rescue => exc
        # TODO fix in foreman
        Rails.logger.error "There was error rendering string: #{string.inspect}\n#{exc} (#{exc.class})\n#{exc.backtrace.join("\n")}"
        raise exc
      end
    end
  end
end

app/models/staypuft/concerns/nic_bonding_extensions.rb
module Staypuft
  module Concerns
    module NicBondingExtensions
      extend ActiveSupport::Concern

      included do
        before_save :ensure_mac
      end

      def ensure_mac
        mac_addresses = self.host.interfaces.where(
            :identifier => attached_devices_identifiers).pluck(:mac).compact
        self.mac =  mac_addresses.first unless mac_addresses.include?(self.mac)
      end
    end
  end
end

app/models/staypuft/concerns/nic_fencing_extensions.rb
module Staypuft
  module Concerns
    module NicFencingExtensions
      extend ActiveSupport::Concern

      included do
        attr_accessible :attrs
      end

      def fencing_enabled?
        attrs['fencing_enabled'] == '1'
      end

      def expose_lanplus?
        attrs['fence_ipmilan_expose_lanplus'] == '1'
      end

    end
  end
end

class ::Nic::Base::Jail < Safemode::Jail
  allow :fencing_enabled?, :attrs, :username, :password, :expose_lanplus?
end

app/models/staypuft/concerns/puppetclass_extensions.rb
module Staypuft::Concerns::PuppetclassExtensions
  extend ActiveSupport::Concern

  included do
    has_many :role_classes, :dependent => :destroy, :class_name => 'Staypuft::RoleClass'
    has_many :roles, :through => :role_classes, :class_name => 'Staypuft::Role'

    has_many :service_classes, :dependent => :destroy, :class_name => 'Staypuft::ServiceClass'
    has_many :services, :through => :service_classes, :class_name => 'Staypuft::Service'

  end
end

app/models/staypuft/deployment/abstract_param_scope.rb
module Staypuft
  class Deployment::AbstractParamScope
    include ActiveModel::Validations
    extend ActiveModel::Callbacks
    extend Deployment::AttributeParamStorage
    define_model_callbacks :save, :only => [:after]

    def self.param_scope
      raise NotImplementedError
    end

    attr_reader :deployment

    def initialize(deployment)
      @deployment = deployment
    end

    def hostgroup
      deployment.hostgroup
    end

    # compatibility with validates_associated
    def marked_for_destruction?
      false
    end

    def attributes=(attr_list)
      attr_list.each { |attr, value| send "#{attr}=", value } unless attr_list.nil?
    end
  end
end

app/models/staypuft/deployment/ceph_service.rb
module Staypuft
  class Deployment::CephService < Deployment::AbstractParamScope
    def self.param_scope
      'ceph'
    end

    param_attr :fsid, :volumes_key, :images_key, :osd_pool_size, :osd_journal_size


    class Jail < Safemode::Jail
      allow :fsid, :volumes_key, :images_key, :mon_initial_members,
            :osd_pool_size, :osd_journal_size
    end

    def set_defaults
      self.fsid = SecureRandom.uuid
      key = ` ceph-authtool --gen-print-key`
      key.chomp! if key
      self.volumes_key = key
      key = ` ceph-authtool --gen-print-key`
      key.chomp! if key
      self.images_key = key
      self.osd_pool_size = ''
      self.osd_journal_size = ''
    end

    def mon_initial_members
      deployment.network_query.controller_shortnames
    end

    def param_hash
      { "fsid" => fsid, "volumes_key" => volumes_key, "images_key" => images_key,
        "osd_pool_size" => osd_pool_size, "osd_journal_size" => osd_journal_size }
    end

  end
end

app/views/staypuft/steps/_cinder_equallogic_form.html.erb
          <div class="eqlx well">
          <h5 class="muted"><a href="#" class="remove"><i class="glyphicon glyphicon-remove-sign ">&nbsp;</i></a>&nbsp;Server #<span class="server_number">1</span></h5>
          <%= text_f e, :san_ip, class: "cinder_equallogic",
                     label:              _(Staypuft::Deployment::CinderService::SanIp::HUMAN) %>
          <%= text_f e, :san_login, class: "cinder_equallogic",
                     label:              _(Staypuft::Deployment::CinderService::SanLogin::HUMAN) %>
          <%= text_f e, :san_password, class: "cinder_equallogic",
                     label:              _(Staypuft::Deployment::CinderService::SanPassword::HUMAN) %>
          <%= text_f e, :pool, class: "cinder_equallogic",
                     label:              _(Staypuft::Deployment::CinderService::EqlxPool::HUMAN) %>
          <%= text_f e, :group_name, class: "cinder_equallogic",
                     label:              _(Staypuft::Deployment::CinderService::EqlxGroupName::HUMAN) %>
          </div>

app/views/staypuft/steps/_wizard_form_buttons.html.erb
<!-- Render Wizard Form Cancel/Back/Submit Buttons -->
<div class="form_actions right" style="text-align: right">

  <!-- Render Cancel Button -->
  <% if is_new && step == Staypuft::Deployment::STEP_SETTINGS %>
    <%= link_to _("Cancel"), deployment_path(@deployment),
                :method  => :delete,
                :confirm => _("This will clear whole deployment configuration. Are you sure?"),
                :class   => "btn btn-danger cancel" %>
  <% else %>
      <%= link_to _("Cancel"), deployment_path(@deployment),
                  :class => "btn btn-danger cancel" %>
  <% end %>

  <!-- Render Back Button -->
  <% unless step == Staypuft::Deployment::STEP_SETTINGS %>
    <a class="btn btn-default" href="<%= previous_wizard_path %>">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <%= _("Back") %>
    </a>
  <% end %>

  <!-- Render Next/Submit Button -->
  <%= button_tag(:type => 'submit', :class => "btn btn-primary pull-right") do %>
    <% if step == Staypuft::Deployment::STEP_CONFIGURATION %>
      <%= _("Submit") %>
    <% else %>
      <%= _("Next") %>
      <span class="glyphicon glyphicon-chevron-right"></span>
    <% end %>
  <% end %>

</div>

app/views/staypuft/steps/network_configuration.html.erb
<%= javascript 'staypuft/subnets_assignment' %>
<%= javascript 'staypuft/new_subnet' %>

<%= render :layout => 'title' do %>
  <%= alert_if_deployed %>

  <div class="well deployment-wizard">
    <div class="wizard-container">
      <%= deployment_wizard 2 %>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= base_errors_for @deployment %>
        <h4><%= _("Available Network Traffic Types") %></h4>
        <div id="subnet_types" class="panel panel-default">
          <div class="panel-body">
            <% @deployment.unassigned_subnet_types.each do |subnet_type| %>
              <%= render 'staypuft/subnet_types/subnet_type_pull', :subnet_type => subnet_type, :deployment => @deployment %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="title_action" class="col-md-12">
        <div class="btn-toolbar pull-right">
          <button type="button" class= "btn btn-success"
                  id="new_subnet_button" data-toggle = "modal"
                  data-target = "#new_subnet_modal">
            <%= _("New Subnet") %>
          </button>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="subnets" class="col-md-12">
        <h4><%= _("Subnets") %></h4>
        <% @subnets.each do |subnet| %>
          <%= render 'staypuft/subnets/drop_zone', :subnet => subnet, :deployment => @deployment %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= form_for(@deployment, :url => wizard_path, :method => 'PUT', :html => {:class => ''}) do |f| %>
          <div class="form_actions">
            <a class="btn btn-default" href="<%= previous_wizard_path %>">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <%= _("Back") %>
            </a>
            <%= link_to _("Cancel"), deployment_path(@deployment),
                        :class => "btn btn-danger cancel" %>
            <%= button_tag(:type => 'submit', :class => "btn btn-primary pull-right", :id => "vip_modal_button" ) do %>
              <%= _("Next") %>
              <span class="glyphicon glyphicon-chevron-right"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal fade" id="new_subnet_modal" tabindex="-1" role="dialog" aria-labelledby="<%= _("New Subnet") %>" aria-hidden="true" data-path="<%= new_staypuft_subnet_path(:deployment_id => @deployment) %>">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title">
              <%= _("New Subnet") %>
            </h2>
          </div>
          <div id="new_subnet_ajax_content">
            <div class="modal-body">
              <div id="new_subnet_form"><%= image_tag '/assets/spinner.gif', style: "display: block; margin-left: auto; margin-right: auto" %></div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal"><%= _("Cancel") %></button>
              <button id="create_subnet_btn" type="button" class="btn btn-primary done" data-dismiss="modal"><%= _("Done") %></button>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="modal fade" id="vip_modal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4><%= image_tag '/assets/spinner.gif', style: "float: left; display: block; margin-left: auto; margin-right: 10px;" %> Generating network configuration. This may take a few moments.</h4>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/staypuft/steps/services_configuration.html.erb
<%= render :layout => 'title' do %>
  <%= alert_if_deployed %>

  <div class="deployment-wizard">
    <%= form_for(@deployment, :url => wizard_path, :method => 'PUT') do |f| %>
      <%= base_errors_for @deployment %>

      <%= deployment_wizard 4 %>
      <div class="form-group tabbed_side_nav_form row">
        <ul class="nav nav-pills nav-stacked col-md-3 configuration" data-tabs="pills">
          <h3><%= _("Services") %></h3>
          <% @services_map.each_with_index do |service_name, i| %>
            <% service = @deployment.send(service_name)
               if service.active?
            %>
              <li class="">
                <a href="#<%= service_name  %>" data-toggle="tab">
                  <%= service_name.capitalize %><span style="visibility: hidden" class ="glyphicon glyphicon-exclamation-sign" />
                </a>
              </li>
              <% end %>
          <% end %>
        </ul>

        <div class="tab-content col-md-9">
          <% @services_map.each_with_index do |service_name, i| %>
            <% service = @deployment.send(service_name)
               if service.active?
            %>
              <div class="tab-pane" id="<%= service_name %>">
                <h3><%= _("%s Service Configuration") % service_name.to_s.capitalize %></h3>
                <div class="<%= "%s-controller-warning" % service_name.to_s %> alert alert-warning base in fade alert-dismissable hide"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><h4 class="alert-heading"><%= _("Warning") %></h4><li><%= _("Only one controller should be assigned when using this option.") %><span class="replace"></span></li></div>
                <div class="<%= "%s-ceph-warning" % service_name.to_s %> alert alert-warning base in fade alert-dismissable hide"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button><h4 class="alert-heading"><%= _("Warning") %></h4><li><%= _("Manual steps are required when deploying with Ceph as a backend for #{service_name.to_s}. Please see documentation for additional steps.") %><span class="replace"></span></li></div>
                <div class="<%= "%s-l2pop-warning" % service_name.to_s %> alert alert-warning base in fade alert-dismissable hide"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button><h4 class="alert-heading"><%= _("Warning") %></h4><li><%= _("When L2 Population is enabled, L3 HA will automatically be turned off.") %><span class="replace"></span></li></div>
                <%= render partial: service_name.to_s, locals: {f: f}%>
              </div>
              <% end %>
          <% end %>
        </div>
      </div>

      <div class="form_actions">
        <a class="btn btn-default" href="<%= previous_wizard_path %>">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <%= _("Back") %>
        </a>
        <%= link_to _("Cancel"), deployment_path(@deployment),
                    :class => "btn btn-danger cancel" %>
        <%= button_tag(:type => 'submit', :class => "btn btn-primary pull-right") do %>
          <%= _("Submit") %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/staypuft/steps/services_selection.html.erb
<%= render :layout => 'title' do %>
  <%= alert_if_deployed %>

  <%= form_for(@deployment, :url => wizard_path, :method => 'PUT') do |f| %>
    <%= base_errors_for @deployment %>

    <%= deployment_wizard 2 %>
    <h3><%= _("Host Groups & Available Services") %></h3>
    <h4><%= "#{@deployment.layout.name} - #{@deployment.layout.networking.capitalize} " + _("Networking") %></h4>

    <div class="clearfix">
        <% @deployment.roles_ordered.each do |role| %>
          <div class="panel panel-default service-box">
            <div class="panel-heading"><strong><%= role.name %></strong></div>
            <div class="panel-body">
              <% role.services.each do |service| %>
                <%= f.label service.name.parameterize.underscore.to_sym, service.name, :class=> "checkbox inline"  do %>
                  <%= f.check_box(service.name.parameterize.underscore.to_sym, :checked => true, :disabled => "disabled") %>
                  <%= service.name %>
                <% end %>
              <% end %>
             </div>
          </div>
        <% end %>
    </div>

    <div class="form_actions">
      <a class="btn btn-default" href="<%= previous_wizard_path %>">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <%= _("Back") %>
      </a>
      <%= link_to _("Cancel"), deployment_path(@deployment),
                  :class => "btn btn-danger" %>
      <%= button_tag(:type => 'submit', :class => "btn btn-primary pull-right") do %>
        <%= _("Next") %>
        <span class="glyphicon glyphicon-chevron-right"></span>
      <% end %>
    </div>
  <% end %>
<% end %>