config/routes.rb
Rails.application.routes.draw do
  scope :module => :staypuft do
    resources :deployments do
      collection do
        get 'auto_complete_search'
      end
      member do
        post 'deploy'
        get 'populate'
        get 'summary'
        get 'edit'
        post 'associate_host'
        post 'unassign_host'
        get 'export_config'
        post 'import_config'
        get 'refresh_assigned_hosts'
      end

      resources :steps

      resources :interface_assignments, :only => [:index, :create, :destroy]

      resources :bonds, :only => [:create, :destroy] do
        member do
          put 'add_slave'
          put 'remove_slave'
          put 'change_mode'
        end
      end
    end

    resources :subnet_typings, :only => [:create, :destroy, :update]

    scope 'staypuft', as: 'staypuft' do
      resources :subnets
    end
  end
end

app/models/concerns/staypuft/puppetclass_extensions.rb
module Staypuft::PuppetclassExtensions
  extend ActiveSupport::Concern

  included do
    has_many :role_classes, :dependent => :destroy, :class_name => 'Staypuft::RoleClass'
    has_many :roles, :through => :role_classes, :class_name => 'Staypuft::Role'

    has_many :service_classes, :dependent => :destroy, :class_name => 'Staypuft::ServiceClass'
    has_many :services, :through => :service_classes, :class_name => 'Staypuft::Service'

  end
end

app/models/settings/staypuft.rb
class Setting::Staypuft < ::Setting
  BLANK_ATTRS << "base_hostgroup"

  def self.load_defaults
    # Check the table exists
    return unless super

    # fixme: not sure about the best way to store AR objects in settings.
    # for now, since we know type, store ID. It might be good to add custom
    # get/set code to decode the ID value into a hostgroup (which methods to call?)
    Setting.transaction do
      [
       self.set("base_hostgroup", _("The base hostgroup which contains the base provisioning config"), nil)
      ].compact.each { |s| self.create s.update(:category => "Setting::Staypuft")}
    end

    true

  end

end

app/models/staypuft/concerns/environment_extensions.rb
module Staypuft::Concerns::EnvironmentExtensions
  extend ActiveSupport::Concern

  module ClassMethods
    def get_discovery
      find_by_name('discovery') or
          raise ::Staypuft::Exception,
                'missing discovery environment, which ensures all its machines are booted ' +
                    'to discovery image.'
    end

    def get_or_create_provisioning
      where(name: 'provisioning').first_or_create
    end
  end
end

app/models/staypuft/concerns/host_details_helper.rb
module Staypuft
  module Concerns
    module HostDetailsHelper
      extend ActiveSupport::Concern

      # Returns memory in GB
      def mem
        mem_arr = self.facts_hash["memorytotal"]
        if mem_arr
          mem_str, mem_unit = mem_arr.split(" ")
          mem_number = mem_str.to_f
          case mem_unit
          when "MB"
            mem_number / 1024
          when "GB"
            mem_number
          when "TB"
            mem_number * 1024
          else
            nil
          end
        else
          nil
        end
      end

      # Returns total number of processes
      def cpus
        self.facts_hash["processorcount"]
      end

      # Returns model
      def model_type
        self.facts_hash["hardwaremodel"]
      end

      # Returns array of NIC names
      def network_interfaces
        if self.facts_hash["interfaces"]
          self.facts_hash["interfaces"].split(",")
        else
          nil
        end
      end

      # Returns architecture
      def architectures
        if self.facts_hash["architecture"]
          self.facts_hash["architecture"].name
        else
          nil
        end
      end

      # Returns array of block device names
      def blockdevices
        if self.facts_hash["blockdevices"]
          self.facts_hash["blockdevices"].split(",")
        else
          []
        end
      end
    end
  end
end

app/models/staypuft/concerns/host_fencing_extensions.rb
module Staypuft
  module Concerns
    module HostFencingExtensions
      extend ActiveSupport::Concern

      FENCING_TYPES = {
        'fence_ipmilan' => 'IPMI'
      }

      included do
        define_method :fencing do
          instance_variable_get(:@fencing_config) or
            instance_variable_set(:@fencing_config, ::Staypuft::Fencing.new(self))
        end

        define_method :fencing= do |value|
          fencing.update(value)
        end

        validates_associated :fencing
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :bmc_nic
end

app/models/staypuft/concerns/host_interface_management.rb
module Staypuft
  module Concerns
    module HostInterfaceManagement
      extend ActiveSupport::Concern

      included do

      end

      def clean_vlan_interfaces
        self.interfaces.virtual.map(&:destroy)
      end

      def interfaces_identifiers
        interfaces = [ self.primary_interface ]
        interfaces += self.respond_to?(:interfaces) ? self.interfaces.where("type <> 'Nic::BMC'").physical.map(&:identifier) : []
        interfaces
      end

      def interfaces_identifiers_with_subnets
        interfaces = [ [self.primary_interface, self.subnet.name] ]
        if self.respond_to?(:interfaces)
          interfaces += self.interfaces.where("type <> 'Nic::BMC'").physical.map do |interface|
            [interface.identifier, ((sub = interface.subnet) ? sub.name :  "")]
          end
        end
        interfaces
      end

      def make_all_interfaces_managed
        self.interfaces.each do |interface|
          interface.managed = true
          interface.save!
        end
      end

      def network_query
        @network_query || NetworkQuery.new(self.hostgroup.deployment, self)
      end

      def primary_interface_is_bonded?
        self.bond_interfaces.any? do |bond|
          bond.attached_devices_identifiers.any? do |interface_identifier|
            self.has_primary_interface? ? self.primary_interface == interface_identifier : false
          end
        end
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :network_query, :primary_interface_is_bonded?
end

app/models/staypuft/concerns/host_open_stack_affiliation.rb
module Staypuft
  module Concerns
    module HostOpenStackAffiliation
      extend ActiveSupport::Concern

      included do
        scope(:in_deployment, lambda do |deployment|
          joins(hostgroup: :deployment_role_hostgroup).
              where(DeploymentRoleHostgroup.table_name => { deployment_id: deployment })
        end)

        scope(:in_roles, lambda do |*roles|
          joins(hostgroup: :deployment_role_hostgroup).
              where(DeploymentRoleHostgroup.table_name => { role_id: roles })
        end)

        scope :in_role, lambda { |role| in_roles(role) }

        has_one :deployment, through: :hostgroup
      end


      def open_stack_deployed?
        !deployment.nil? && !deployment.in_progress? &&
        open_stack_environment_set? && open_stack_assigned?
      end

      def open_stack_environment_set?
        open_stack_assigned? &&
        respond_to?(:environment) &&
        environment != Environment.get_discovery
      end

      def open_stack_assigned?
        respond_to?(:hostgroup) &&
            hostgroup.try(:parent).try(:parent) == Hostgroup.get_base_hostgroup
      end

      def open_stack_unassign
        self.hostgroup = nil
        save!
      end
    end
  end
end

class ::Host::Managed::Jail < Safemode::Jail
  allow :deployment
end

app/models/staypuft/deployment.rb
module Staypuft
  class Deployment < ActiveRecord::Base

    # Form step states
    STEP_INACTIVE      = :inactive
    STEP_SETTINGS      = :settings
    STEP_CONFIGURATION = :configuration
    STEP_COMPLETE      = :complete
    STEP_OVERVIEW      = :overview
    STEP_NETWORKING    = :networking

    NEW_NAME_PREFIX = 'uninitialized_'

    # supporting import/export
    EXPORT_PARAMS   = [:amqp_provider, :networking, :layout_name, :platform]
    EXPORT_SERVICES = [:nova, :neutron, :glance, :cinder, :passwords, :ceph]

    attr_accessible :description, :name, :layout_id, :layout,
                    :amqp_provider, :layout_name, :networking, :platform,
                    :custom_repos
    after_save :update_hostgroup_name
    after_validation :check_form_complete

    belongs_to :layout

    # needs to be defined before hostgroup association
    belongs_to :hostgroup, :dependent => :destroy

    has_many :deployment_role_hostgroups, :dependent => :destroy
    has_many :child_hostgroups,
             :through    => :deployment_role_hostgroups,
             :class_name => 'Hostgroup',
             :source     => :hostgroup

    has_many :roles,
             :through => :deployment_role_hostgroups
    has_many :roles_ordered,
             :through => :deployment_role_hostgroups,
             :source  => :role,
             :order   => "#{::Staypuft::DeploymentRoleHostgroup.table_name}.deploy_order"

    has_many :services, :through => :roles
    has_many :hosts, :through => :child_hostgroups

    has_many :subnet_typings, :dependent => :destroy
    has_many :subnet_types, :through => :subnet_typings
    has_many :subnets, :through => :subnet_typings

    validates :name, :presence => true, :uniqueness => true

    validates :layout, :presence => true
    validates :hostgroup, :presence => true

    validate :all_required_subnet_types_associated, :if => Proc.new { |o| o.form_step == STEP_NETWORKING }

    after_validation :check_form_complete
    before_save :update_layout
    after_save :update_based_on_settings

    SCOPES = [[:nova, :@nova_service, NovaService],
              [:neutron, :@neutron_service, NeutronService],
              [:glance, :@glance_service, GlanceService],
              [:cinder, :@cinder_service, CinderService],
              [:passwords, :@passwords, Passwords],
              [:ceph, :@ceph, CephService]]

    SCOPES.each do |name, ivar, scope_class|
      define_method name do
        instance_variable_get ivar or
            instance_variable_set ivar, scope_class.new(self)
      end
      after_save { send(name).run_callbacks :save }
    end

    validates_associated :nova, :if => lambda { |d| d.form_step_is_past_configuration? && d.nova.active? }
    validates_associated :neutron, :if => lambda { |d| d.form_step_is_past_configuration? && d.neutron.active? }
    validates_associated :glance, :if =>  lambda {|d| d.form_step_is_past_configuration? && d.glance.active? }
    validates_associated :cinder, :if =>  lambda {|d| d.form_step_is_past_configuration? && d.cinder.active? }
    validates_associated :passwords

    def initialize(attributes = {}, options = {})
      super({ amqp_provider: AmqpProvider::RABBITMQ,
              layout_name:   LayoutName::NON_HA,
              networking:    Networking::NEUTRON,
              platform:      Platform::RHEL7 }.merge(attributes),
            options)

      self.hostgroup = Hostgroup.new(name: name, parent: Hostgroup.get_base_hostgroup)

      self.nova.set_defaults
      self.neutron.set_defaults
      self.glance.set_defaults
      self.cinder.set_defaults
      self.passwords.set_defaults
      self.ceph.set_defaults
      self.layout = Layout.where(:name       => self.layout_name,
                                 :networking => self.networking).first
    end

    extend AttributeParamStorage

    # Helper method for looking up a Deployment based on a foreman task
    def self.find_by_foreman_task(foreman_task)
      task = ForemanTasks::Lock.where(task_id: foreman_task.id,
                                                     name: :deploy,
                                                     resource_type: 'Staypuft::Deployment').first
      unless task.nil?
        Deployment.find(task.resource_id)
      else
        nil
      end

    end

    # Returns a list of hosts that are currently being deployed.
    def in_progress_hosts(hostgroup)
      return in_progress? ? hostgroup.openstack_hosts : {}
    end

    # Helper method for checking whether this deployment is in progress or not.
    def in_progress?
      ForemanTasks::Lock.locked? self, nil
    end

    def hide_ceph_notification?
      ceph_hostgroup.hosts.empty?
    end

    # Helper method for getting the in progress foreman task for this
    # deployment.
    def task
      in_progress? ? ForemanTasks::Lock.colliding_locks(self, nil).first.task : nil
    end

    # Returns all deployed hosts with no errors (default behaviour).  Set
    # errors=true to return all deployed hosts that have errors
    def deployed_hosts(hostgroup, errors=false)
      in_progress? ? {} : hostgroup.openstack_hosts(errors)
    end

    def progress_summary
      self.in_progress? ? self.task.humanized[:output] : nil
    end

    # Helper method for getting the progress of this deployment
    def progress
      if self.in_progress?
        (self.task.progress * 100).round(1)
      elsif self.deployed?
        100
      else
        0
      end
    end

    def self.param_scope
      'deployment'
    end

    module AmqpProvider
      RABBITMQ = 'rabbitmq'
      QPID     = 'qpid'
      LABELS   = { RABBITMQ => N_('RabbitMQ'), QPID => N_('Qpid') }
      TYPES    = LABELS.keys
      HUMAN    = N_('Messaging Provider')
    end

    module Networking
      NOVA    = 'nova'
      NEUTRON = 'neutron'
      LABELS  = { NEUTRON => N_('Neutron Networking'), NOVA => N_('Nova Network') }
      TYPES   = LABELS.keys
      HUMAN   = N_('Networking')
    end

    module LayoutName
      NON_HA = 'Controller / Compute'
      HA     = 'High Availability Controllers / Compute'
      LABELS = { NON_HA => N_('Controller / Compute'),
                 HA     => N_('High Availability Controllers / Compute') }
      TYPES  = LABELS.keys
      HUMAN  = N_('High Availability')
    end

    module Platform
      RHEL7  = 'rhel7'
      RHEL6  = 'rhel6'
      LABELS = { RHEL7 => N_('Red Hat Enterprise Linux OpenStack Platform 5 with RHEL 7')}
      TYPES  = LABELS.keys
      HUMAN  = N_('Platform')
    end

    param_attr :amqp_provider, :networking, :layout_name, :platform
    validates :amqp_provider, :presence => true, :inclusion => { :in => AmqpProvider::TYPES }
    validates :networking, :presence => true, :inclusion => { :in => Networking::TYPES }
    validates :layout_name, presence: true, inclusion: { in: LayoutName::TYPES }
    validates :platform, presence: true, inclusion: { in: Platform::TYPES }

    class Jail < Safemode::Jail
      allow :amqp_provider, :networking, :layout_name, :platform, :nova_networking?, :neutron_networking?,
        :nova, :neutron, :glance, :cinder, :passwords, :ceph, :ha?, :non_ha?,
        :hide_ceph_notification?, :network_query, :has_custom_repos?, :custom_repos_paths
    end

    # TODO(mtaylor)
    # Use conditional validations to validate the deployment multi-step form.
    # deployment.form_step should be used to check the form step the user is
    # currently on.
    # e.g.
    # validates :name, :presence => true, :if => :form_step_is_configuration?

    scoped_search :on => :name, :complete_value => :true

    def self.available_locks
      [:deploy]
    end

    def services_hostgroup_map
      deployment_role_hostgroups.map do |deployment_role_hostgroup|
        deployment_role_hostgroup.services.reduce({}) do |h, s|
          h.update s => deployment_role_hostgroup.hostgroup
        end
      end.reduce(&:merge)
    end

    def deployed?
      self.hosts.any?(&:open_stack_deployed?)
    end

    def form_step_is_configuration?
      self.form_step.to_sym == Deployment::STEP_CONFIGURATION
    end

    def form_step_is_past_configuration?
      self.form_step_is_configuration? || self.form_complete?
    end

    def form_complete?
      self.form_step.to_sym == Deployment::STEP_COMPLETE
    end

    def ha?
      self.layout_name == LayoutName::HA
    end

    def non_ha?
      self.layout_name == LayoutName::NON_HA
    end

    def nova_networking?
      networking == Networking::NOVA
    end

    def neutron_networking?
      networking == Networking::NEUTRON
    end

    def horizon_url
      if ha?
        "http://#{network_query.get_vip(:horizon_public_vip)}"
      else
        network_query.controller_ips(Staypuft::SubnetType::PUBLIC_API).empty? ? nil : "http://#{network_query.controller_ip(Staypuft::SubnetType::PUBLIC_API)}"
      end
    end

    def controller_hostgroup
      Hostgroup.includes(:deployment_role_hostgroup).
        where(DeploymentRoleHostgroup.table_name => { deployment_id: self,
                                                      role_id:       Staypuft::Role.controller }).
        first
    end

    def unassigned_subnet_types
      self.layout.subnet_types - self.subnet_types
    end

    def unassigned_pxe_default_subnet_types
      self.layout.subnet_types.pxe_defaults - self.subnet_types
    end

    def ceph_hostgroup
      Hostgroup.includes(:deployment_role_hostgroup).
        where(DeploymentRoleHostgroup.table_name => { deployment_id: self,
                                                      role_id:       Staypuft::Role.cephosd }).
        first
    end

    def network_query
      @network_query || NetworkQuery.new(self)
    end

    def has_custom_repos?
      self.custom_repos.present?
    end

    def custom_repos_paths
      self.custom_repos.split("\n")
    end

    private

    def update_layout
      self.layout = Layout.where(:name => layout_name, :networking => networking).first
    end

    def update_based_on_settings

app/views/staypuft/deployments/_assigned_hosts.html.erb
<% if hosts.any? %>
<h4 class="pull-left"><%= _("Assigned Hosts") %></h4>
<div class="" id="table_assigned_hosts">
  <%= form_tag(unassign_host_deployment_path(id: @deployment), class: 'form-horizontal association', method: 'post') do |f| %>
    <div class="pull-right top_actions">
      <%= render partial: "hosts_filter" %>
      <div class="pull-right">
        <button type="button" class= "btn btn-default btn-sm"
                id="configure_networks_button" data-toggle = "modal"
                data-target = "#configure_networks_modal" disabled="true"><%= _("Configure Networks") %></button>
        <%= submit_tag _("Unassign Hosts"), :class => "btn btn-primary btn-sm", :disabled => true, :id => "unassign_hosts_button" %>
      </div>
    </div>
    <div id="assigned-hosts_table"><%= render partial: "hosts_table", locals: { hosts: hosts, deployment_role_col: true } %></div>
    <div class="modal fade" id="configure_networks_modal" tabindex="-1" role="dialog" aria-labelledby="<%= _("Configure Networks") %>" aria-hidden="true" data-path="<%= deployment_interface_assignments_path(@deployment.id)  %>" data-refresh_path="<%= refresh_assigned_hosts_deployment_path(@deployment.id)%>">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title" id="configure_networks_modal_label">
              <%= _("Configure Networks") %>
            </h2>
          </div>
          <div class="modal-body">
            <div id="interfaces"><%= image_tag '/assets/spinner.gif', style: "display: block; margin-left: auto; margin-right: auto" %></div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><%= _("Cancel") %></button>
            <button type="button" class="btn btn-primary done" data-dismiss="modal"><%= _("Done") %></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% else %>
  <div class="association">
    <h4><%= _("Assigned Hosts") %></h4>
    <div class="alert alert-warning">
      <span class="glyphicon glyphicon-warning-sign">&nbsp;</span>
      <%= _("There are no currently assigned hosts.") %>
    </div>
  </div>
<% end %>

app/views/staypuft/deployments/_deployment_networking.html.erb
<h1>TODO: Deployment Networking Tab</h1>

app/views/staypuft/deployments/_deployment_progress_page_header.html.erb
<% if @deployment = Staypuft::Deployment.find_by_foreman_task(@task) %>
  <div style='width: 70%; display: inline-block'>
    <h1 style='margin-top: 0'>Deployment Status</h1>
  </div>
  
  <div style='display: inline-block; float: right'>
    <% if Staypuft::Deployment.find_by_foreman_task(@task) %>
      <%= link_to _('Return to deployment'), deployment_path(@deployment) %>
    <% end %>
  </div>
<% end %>

app/views/staypuft/deployments/_free_hosts.html.erb
<% if hosts.exists? %>
<h4 class="pull-left"><%= _("Unassigned Hosts") %></h4>
<div class="" id="table_free_hosts">
  <%= form_tag(associate_host_deployment_path(id: @deployment), class: 'form-horizontal association') do |f| %>
    <div class="pull-right top_actions">
      <%= render partial: "hosts_filter" %>
      <div class="pull-right">
        <%= submit_tag _("Configure Networks"), :class => "btn btn-default btn-sm", :style => "visibility: hidden" %>
        <button type="button" class= "btn btn-primary btn-sm"
                id="assign_hosts_modal" data-toggle = "modal"
                data-target = "#role_modal" disabled="true"><%= _("Assign Hosts") %></button>
        </div>
    </div>
    <%= render partial: "hosts_table", locals: { hosts: hosts, operating_system_col: true } %>
    <div class="modal fade" id="role_modal" tabindex="-1" role="dialog" aria-labelledby="Deployment Roles" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title" id="role_modal_label">
              <span class="glyphicon glyphicon-th-list">
              </span> <%= _("Deployment Roles") %>
            </h2>
          </div>
          <div class="modal-body">
            <h3><%= _("Choose a deployment role to assign these to:") %></h3>
            <div>
              <% @deployment.child_hostgroups.each do |child_hostgroup| %>
                <div class="form-inline">
                  <%= radio_button_tag(:hostgroup_id, child_hostgroup.id, false) %>
                  <%= label_tag(child_hostgroup.id, child_hostgroup.name) %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><%= _("Cancel") %></button>
            <%= submit_tag _("Assign Hosts"), :class => "btn btn-primary btn-sm" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% else %>
  <div class="association">
    <h4><%= _("Unassigned Hosts") %></h4>
    <div class="alert alert-warning">
      <span class="glyphicon glyphicon-warning-sign">&nbsp;</span>
      <%= _("All available hosts have been already assigned.") %>
    </div>
  </div>
<% end %>

app/views/staypuft/deployments/_hosts_table.html.erb
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th class="ca">
            <%= tag :input, type: 'checkbox', class: 'check_all' %>
          </th>
          <th><%= sort :name, :as => _('Name') %></th>
          <% if local_assigns[:deployment_role_col] %>
            <th><%= _("Deployment Role") %></th>
          <% end %>
          <% if local_assigns[:operating_system_col] %>
            <th><%= _("Operating System") %></th>
          <% end %>
          <th><%= _("CPUs") %><br/><span class="text-muted small"><%= _("(cores)") %></span></th>
          <th><%= _("Memory") %><br/><span class="text-muted small"><%= _("(GB)") %></span></th>
          <th><%= _("Storage") %></th>
          <% if local_assigns[:deployment_role_col] %>
            <th><%= _("NICs (Subnet)") %></th>
          <% else %>
            <th><%= _("NICs") %></th>
          <% end %>
          <th class="hidden-s hidden-xs"><%= sort :ip, :as => _('IP Address') %></th>
        </tr>
      </thead>
      <tbody class="searchable">
        <% hosts.each do |host| %>
          <tr class="checkbox_highlight">
            <td class="ca">
              <%= check_box_tag 'host_ids[]',
                                host.id,
                                false,
                                id:       "host_ids_#{host.id}" %>
            </td>
            <td class="ellipsis">
             <%= host_label(host) %>
            </td>
            <% if local_assigns[:deployment_role_col] %>
            <td class="ellipsis">
              <%= link_to(host.hostgroup.role, hosts_path(:search => "os_description = #{host.hostgroup.role}")) if host.hostgroup %>
            </td>
            <% end %>
            <% if local_assigns[:operating_system_col] %>
            <td class="ellipsis">
              <%= link_to(host.os.to_label, hosts_path(:search => "os_description = #{host.os.description}")) if host.respond_to?(:os) && host.os %>
            </td>
            <% end %>
            <td><%= host.cpus if host.respond_to?(:cpus) %></td>
            <td><%= host.mem if host.respond_to?(:mem) %></td>
            <td><%= host_disks(host) %></td>
            <% if local_assigns[:deployment_role_col] %>
              <td><%= host_nics_with_subnets(host) %></td>
            <% else %>
              <td><%= host_nics(host) %></td>
            <% end %>
            <td class="hidden-s hidden-xs"><%= host.ip %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <script type="text/javascript">
      //small replacement to make the behavior the same as it was before we had a refreshs
      jQuery('a[href*="refresh_assigned_hosts"]').each(function(){
        var _href = $(this).attr('href');
        $(this).attr('href', _href.replace(/refresh_assigned_hosts/, ''));
      })
    </script>

app/views/staypuft/deployments/summary.html.erb
<% title _("%s Configuration Parameters") % @deployment.name %>
<% content_for(:top_actions) do %>
  <%= link_to _("Back to Deployment"), deployment_path(@deployment.id), :class => "btn btn-link" %>
  <%= link_to(icon_text("cloud-upload", _("Import")),
              {},
              { :class  => "btn btn-default",
                :remote => true,
                :rel    => 'popover',
                :data   => { 'content'        => "#{render partial: 'import_form'}",
                             'original-title' => _('Import Config'),
                             'placement'      => 'left' } }) %>
  <%= link_to(icon_text("cloud-download", _("Export")),
              export_config_deployment_path(@deployment.id), :class => "btn btn-default") %>
  <%= link_to _("Edit"), edit_deployment_path(@deployment.id),
              :class => @deployment.in_progress? ? %w(btn btn-default disabled) : %w(btn btn-default) %>
<% end %>

<div class="col-md-12">
  <div class="form-group tabbed_side_nav_form row">
    <ul class="nav nav-pills nav-stacked col-md-3" data-tabs="pills">
      <h3><%= _("Services") %></h3>
      <% @service_hostgroup_map.each_with_index do |(service, hostgroup), i| %>
        <li class="<%= 'active' if i == 0 %>">
          <a href="#<%= service.name.parameterize.underscore %>" data-toggle="tab">
            <%= service.name %>
          </a>
        </li>
      <% end %>
    </ul>

    <div class="tab-content col-md-9">
      <% @service_hostgroup_map.each_with_index do |(service, hostgroup), i| %>
        <div class="tab-pane <%= 'active' if i == 0 %>" id="<%= service.name.parameterize.underscore %>">
          <h3><%= "#{service.name} " + _("Service Configuration") %></h3>
          <% if (params_hash = service.ui_params_for_form(hostgroup)).size > 0 %>
            <% params_hash.each do |param_hash| %>
              <div class="row">
                <div class="col-md-4 control-label">
                  <%= label_tag param_hash[:param_key].key %>
                </div>
                <div class="col-md-8">
                  <%= text_field_tag format("staypuft_deployment[hostgroup_params][%s][puppetclass_params][%s][%s]",
                                            param_hash[:hostgroup].id,
                                            param_hash[:puppetclass].id,
                                            param_hash[:param_key].key),
                                     value     = param_hash[:hostgroup].current_param_value_str(param_hash[:param_key]),
                                     :class    => "form-control",
                                     :size     => "45",
                                     disabled: true %>
                  <% if Staypuft::Concerns::LookupKeyExtensions.has_erb? value %>
                    <span class="help-block">
                      <%= _('evaluates to: ') %>
                      <%= Staypuft::Concerns::LookupKeyExtensions.evaluate_value param_hash[:hostgroup], value %>
                    </span>
                  <% end %>
                </div>
              </div>
              <br/>
            <% end %>
          <% else %>
            <p><%= _("No configuration needed for this service.") %></p>
          <% end %>
          <% # render "puppetclasses/classes_parameters", { :obj => service.hostgroups.first }   %>
        </div>
      <% end %>
    </div>
  </div>
</div>